version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "local" 

  # Dynamodb UI
  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin:latest"
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://localstack:4566
      AWS_REGION: ${AWS_REGION:-local}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-local}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-local}
    networks:
      - "local"

networks:
  local:
    driver: "bridge"